### ISSUE TITLE
Performance issues with 265k certfificates in inventory

### ISSUE THREAD

**Issue by semik** [CZERTAINLY/CZERTAINLY-Core#789]
I've CZERTAINLY with 265k certificates and facing several performance related issues. 

**Dashboard**  takes 30+s to load
![image](https://github.com/user-attachments/assets/70a6fa45-bd04-4bfc-ac43-06ac83ac3a17)
I've enabled logging slow PostgreSQL queries exceeding 5s is this one:
```
2024-07-15 11:58:17.806 CEST [14274] czertainlyuser@czertainlydb LOG:  duration: 6639.461 ms  execute <unnamed>: select distinct c1_0.uuid,c1_0.i_author,c1_0.basic_constraints,c1_0.certificate_content_id,c1_0.certificate_request_uuid,c1_0.certificate_type,c1_0.certificate_validation_result,c1_0.common_name,c1_0.compliance_result,c1_0.compliance_status,c1_0.i_cre,c1_0.extended_key_usage,c1_0.fingerprint,g1_0.object_uuid,g1_1.uuid,g1_1.i_author,g1_1.i_cre,g1_1.description,g1_1.email,g1_1.name,g1_1.i_upd,c1_0.issuer_certificate_uuid,c1_0.issuer_common_name,c1_0.issuer_dn,c1_0.issuer_dn_normalized,c1_0.issuer_serial_number,c1_0.key_uuid,c1_0.key_size,c1_0.key_usage,c1_0.not_after,c1_0.not_before,o1_0.uuid,o1_0.object_uuid,o1_0.owner_username,o1_0.owner_uuid,o1_0.resource,c1_0.public_key_algorithm,c1_0.public_key_fingerprint,r1_0.uuid,r1_0.acme_profile_uuid,r1_0.i_author,r1_0.authority_certificate_uuid,r1_0.authority_instance_name,r1_0.authority_instance_ref_uuid,r1_0.i_cre,r1_0.description,r1_0.enabled,r1_0.name,r1_0.scep_profile_uuid,r1_0.i_upd,c1_0.ra_profile_uuid,c1_0.serial_number,c1_0.signature_algorithm,c1_0.source_certificate_uuid,c1_0.state,c1_0.status_validation_timestamp,c1_0.subject_alternative_names,c1_0.subject_dn,c1_0.subject_dn_normalized,c1_0.trusted_ca,c1_0.i_upd,c1_0.user_uuid,c1_0.validation_status from core.certificate c1_0 left join (core.group_association g1_0 join core."group" g1_1 on g1_1.uuid=g1_0.group_uuid) on c1_0.uuid=g1_0.object_uuid and (g1_0.resource = 'CERTIFICATE')  and (g1_0.resource = 'CERTIFICATE')  left join core.owner_association o1_0 on o1_0.object_uuid=c1_0.uuid left join core.ra_profile r1_0 on r1_0.uuid=c1_0.ra_profile_uuid
```
In this situation SQL query took 6.6s but the whole process of displaying dashboard took 33s, that mean that ~26s was spend somewhere in CZERTAINLY. 

**Certificates list** takes 50+s to load
![image](https://github.com/user-attachments/assets/79d47e17-81c0-4b39-bd32-aec05b15dc6f)

PostgreSQL query:
```
2024-07-15 12:01:46.047 CEST [14307] czertainlyuser@czertainlydb LOG:  duration: 9781.259 ms  execute <unnamed>: select distinct c1_0.uuid,c1_0.i_author,c1_0.basic_constraints,c1_0.certificate_content_id,c1_0.certificate_request_uuid,c1_0.certificate_type,c1_0.certificate_validation_result,c1_0.common_name,c1_0.compliance_result,c1_0.compliance_status,c1_0.i_cre,c1_0.extended_key_usage,c1_0.fingerprint,g1_0.object_uuid,g1_1.uuid,g1_1.i_author,g1_1.i_cre,g1_1.description,g1_1.email,g1_1.name,g1_1.i_upd,c1_0.issuer_certificate_uuid,c1_0.issuer_common_name,c1_0.issuer_dn,c1_0.issuer_dn_normalized,c1_0.issuer_serial_number,k1_0.uuid,k1_0.i_author,k1_0.i_cre,k1_0.description,k1_0.name,k1_0.token_instance_uuid,k1_0.token_profile_uuid,k1_0.i_upd,c1_0.key_size,c1_0.key_usage,c1_0.key_uuid,c1_0.not_after,c1_0.not_before,o1_0.uuid,o1_0.object_uuid,o1_0.owner_username,o1_0.owner_uuid,o1_0.resource,c1_0.public_key_algorithm,c1_0.public_key_fingerprint,r1_0.uuid,r1_0.acme_profile_uuid,r1_0.i_author,r1_0.authority_certificate_uuid,r1_0.authority_instance_name,r1_0.authority_instance_ref_uuid,r1_0.i_cre,r1_0.description,r1_0.enabled,r1_0.name,r1_0.scep_profile_uuid,r1_0.i_upd,c1_0.ra_profile_uuid,c1_0.serial_number,c1_0.signature_algorithm,c1_0.source_certificate_uuid,c1_0.state,c1_0.status_validation_timestamp,c1_0.subject_alternative_names,c1_0.subject_dn,c1_0.subject_dn_normalized,c1_0.trusted_ca,c1_0.i_upd,c1_0.user_uuid,c1_0.validation_status from core.certificate c1_0 left join (core.group_association g1_0 join core."group" g1_1 on g1_1.uuid=g1_0.group_uuid) on c1_0.uuid=g1_0.object_uuid and (g1_0.resource = 'CERTIFICATE')  and (g1_0.resource = 'CERTIFICATE')  left join core.owner_association o1_0 on o1_0.object_uuid=c1_0.uuid left join core.ra_profile r1_0 on r1_0.uuid=c1_0.ra_profile_uuid left join core.cryptographic_key k1_0 on k1_0.uuid=c1_0.key_uuid where 1=1 order by c1_0.i_cre desc
```

In this situation SQL query took 9.8s but the whole process of displaying list took 52s, that mean that ~42s was spend somewhere in CZERTAINLY. 

**Scheduler**

I've already filled one issue on scheduler (https://github.com/3KeyCompany/CZERTAINLY-Core/issues/786) after increasing number of certs from 120k to 265k scheduler stopped to working at all.
![image](https://github.com/user-attachments/assets/f084f38a-515b-4910-bbba-4fb4841364a6)

The last successful run took 02:37:39 to finish. I was adding certs to CZERTAINLY instance during whole weekend but, scheduler stopped working on Saturday evening.

I've found in logs interesting messages:
```
[2024-07-15 06:17:25.793] ERROR [org.springframework.amqp.rabbit.RabbitListenerEndpointContainer#3-2] [org.hibernate.engine.jdbc.spi.SqlExceptionHelper - 138]: ERROR: deadlock detected

[2024-07-15 06:17:25.813] WARN  [org.springframework.amqp.rabbit.RabbitListenerEndpointContainer#3-2] [com.czertainly.core.service.impl.CertificateServiceImpl - 708]: Unable to validate the certificate Certificate[uuid=f5d2367d-8369-40d6-ba8c-335c71512b11,commonName=d66cbd4649ac.dcer.azurecertificateservice.azure-int.net,serialNumber=a6ee8684b3d4d5db1f0e777c2e14887]: could not execute batch; SQL [update core.certificate set status_validation_timestamp=?, i_upd=? where uuid=?]
[2024-07-15 06:17:25.814] WARN  [org.springframework.amqp.rabbit.RabbitListenerEndpointContainer#3-2] [com.czertainly.core.messaging.producers.NotificationProducer - 48]: Recipients for notification CERTIFICATE_STATUS_CHANGED is empty. Message: NotificationMessage (CERTIFICATE_STATUS_CHANGED, CERTIFICATE, f5d2367d-8369-40d6-ba8c-335c71512b11, [], com.czertainly.api.model.connector.notification.data.NotificationDataCertificateStatusChanged@57b275f0)
[2024-07-15 06:17:25.816] WARN  [org.springframework.amqp.rabbit.RabbitListenerEndpointContainer#3-2] [com.czertainly.core.service.impl.CertificateServiceImpl - 1006]: Scheduled task was unable to update status of the certificate. Certificate Certificate[uuid=f5d2367d-8369-40d6-ba8c-335c71512b11,commonName=d66cbd4649ac.dcer.azurecertificateservice.azure-int.net,serialNumber=a6ee8684b3d4d5db1f0e777c2e14887]. Error: Transaction silently rolled back because it has been marked as rollback-only
org.springframework.transaction.UnexpectedRollbackException: Transaction silently rolled back because it has been marked as rollback-only
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:752)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711)
        at com.czertainly.core.service.impl.CertificateServiceImpl.updateCertificatesStatusScheduled(CertificateServiceImpl.java:1000)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
....
[2024-07-15 06:17:25.835] WARN  [org.springframework.amqp.rabbit.RabbitListenerEndpointContainer#3-2] [org.springframework.amqp.rabbit.listener.ConditionalRejectingErrorHandler - 170]: Execution of Rabbit message listener failed.
org.springframework.amqp.rabbit.support.ListenerExecutionFailedException: Listener method 'public void com.czertainly.core.messaging.listeners.SchedulerListener.processMessage(com.czertainly.api.model.scheduler.SchedulerJobExecutionMessage)' threw exception
...
        ... 15 common frames omitted
```

And later:
```
[2024-07-15 09:50:59.986] ERROR [org.springframework.amqp.rabbit.RabbitListenerEndpointContainer#3-12] [org.hibernate.engine.jdbc.spi.SqlExceptionHelper - 138]: HikariPool-1 - Connection is not available, request timed out after 30689ms.
[2024-07-15 09:50:59.990] WARN  [org.springframework.amqp.rabbit.RabbitListenerEndpointContainer#3-12] [org.springframework.amqp.rabbit.listener.ConditionalRejectingErrorHandler - 170]: Execution of Rabbit message listener failed.
org.springframework.amqp.rabbit.support.ListenerExecutionFailedException: Listener method 'public void com.czertainly.core.messaging.listeners.SchedulerListener.processMessage(com.czertainly.api.model.scheduler.SchedulerJobExecutionMessage)' threw exception
        at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:286)
...
Caused by: org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction
        at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:466)
        ...
        ... 15 common frames omitted
Caused by: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
        at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:49)
...
        ... 74 common frames omitted
[2024-07-15 09:51:03.619] WARN  [org.springframework.amqp.rabbit.RabbitListenerEndpointContainer#3-3] [org.hibernate.engine.jdbc.spi.SqlExceptionHelper - 133]: SQL Error: 0, SQLState: null
[2024-07-15 09:51:03.619] ERROR [org.springframework.amqp.rabbit.RabbitListenerEndpointContainer#3-3] [org.hibernate.engine.jdbc.spi.SqlExceptionHelper - 138]: HikariPool-1 - Connection is not available, request timed out after 30757ms.
[2024-07-15 09:51:03.621] WARN  [org.springframework.amqp.rabbit.RabbitListenerEndpointContainer#3-3] [com.zaxxer.hikari.pool.ProxyConnection - 177]: HikariPool-1 - Connection org.postgresql.jdbc.PgConnection@3b0af31f marked as broken because of SQLSTATE(57P01), ErrorCode(0)
org.postgresql.util.PSQLException: FATAL: terminating connection due to administrator command
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
```
I think errors at [2024-07-15 09:50:59.986] were trigered by disabling/enabling `updateCertificateStatusJob`. However after appliance restart I'm unable to reproduce such error. 

**Versions**

I'm conducting my tests on Virtual Appliance running on Linux host with i7-6700 CPU @ 3.40GHz. Appliance have 4 vCPU and 12GB RAM. I'm using CZERTAINLY 2.12.0 (despite of hostname in screenschots)

**Logs**

I'm attaching logs from czertainly-core, messaging.logs, scheduler.logs and postgresql-15-main.log

Slow SQL queries loging was activated at 2024-07-14 09:15:37.479 CEST.

Logs needed to be truncated because github limits, but they are [attached](https://github.com/user-attachments/files/16233370/logs.tar.gz). I noted ` Unable to acquire JDBC Connection`. Time of that record id different from moment, I've been restarting PSQL to enable slow queries. And I also checked that i've max connection = 250 and CZERTAINLY is using around 80 so number off connections should  not be an issue.

**Comment by semik** [comment]
I believe that dashboard & cert. list perf. issues are already resolved.
